In [11]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup

# initialize browser
driver = webdriver.Chrome()
driver.get("https://www.wipo.int/gii-ranking/en/rank")

wait = WebDriverWait(driver, 10)
element = wait.until(EC.presence_of_element_located((By.CLASS_NAME, "w-full")))

html_source = driver.page_source

# save to soup for scraping
soup = BeautifulSoup(html_source, 'html.parser')

# save to file just in case
with open('page_source.html', 'w', encoding='utf-8') as f:
    f.write(html_source)
    
print("HTML saved to 'page_source.html'")

driver.quit()

HTML saved to 'page_source.html'

In [15]:
tables_div = soup.find(class_="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-20 gap-y-10")

In [ ]:
from io import StringIO
import pandas as pd

tables = pd.read_html(StringIO(str(tables_div)))

In [36]:
df_tables = pd.concat(tables, ignore_index=True).sort_values("GII rank")
df_tables.to_csv("GII_rank")

In [80]:
df = pd.read_csv("GII_2011_2024_long_format.tsv", sep='\t')
df

     Country  Year  Rank  Score
0        AGO  2011    -1  -1.00
1        AGO  2012   135  22.20
2        AGO  2013   135  23.46
3        AGO  2014   135  23.82
4        AGO  2015   120  26.20
...      ...   ...   ...    ...
2081     ZWE  2020   120  19.97
2082     ZWE  2021   113  21.90
2083     ZWE  2022   107  18.10
2084     ZWE  2023   117  16.50
2085     ZWE  2024   118  15.60

[2086 rows x 4 columns]

In [64]:
import country_converter as coco
import numpy as np

converted_country = coco.convert(names=df.Country, to="name")

In [81]:
df.rename({"Country":"CountryISO"}, axis=1, inplace=True)
df['CountryName'] = converted_country

In [82]:
df_country_iso = df.groupby(['CountryName', 'CountryISO'], as_index=False).count()[['CountryName', 'CountryISO']]
df_country_iso.head()

  CountryName CountryISO
0     Albania        ALB
1     Algeria        DZA
2      Angola        AGO
3   Argentina        ARG
4     Armenia        ARM

In [84]:
df_country_iso.to_csv('country_iso.csv', index=False)